version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          export TAG="${DOCKERHUB_USER}/grpc-generator-go:${CIRCLE_BRANCH}"
          export TAG_LATEST="${DOCKERHUB_USER}/grpc-generator-go:latest"
          
          docker build --platform=linux/amd64 -t ${TAG}-amd64 ./amd64
          docker build --platform=linux/arm64 -t ${TAG}-arm64 ./arm64
          
          docker manifest create $TAG --amend ${TAG}-amd64 --amend ${TAG}-arm64
          docker manifest create $TAG_LATEST --amend ${TAG}-amd64 --amend ${TAG}-arm64
          
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
          docker manifest push $TAG
          docker manifest push $TAG_LATEST

workflows:
  version: 2
  build_tag:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
