version: 2.1
commands:
  build-image-and-push:
    parameters:
      tag:
        type: string
      arch:
        type: string
    steps:
      - run: |
          docker build --platform=linux/<<parameters.arch>> -t <<parameters.tag>>-<<parameters.arch>> ./<<parameters.arch>>
          docker push <<parameters.tag>>-<<parameters.arch>>
jobs:
  - build_arm64:
      resource_class: arm.medium
      docker: docker:20.10
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_USER
      steps:
        - setup_remote_docker:
            docker_layer_caching: true
        - checkout
        - build-image-and-push:
            tag: "${DOCKERHUB_USER}/grpc-generator-go:${CIRCLE_TAG}"
            arch: "arm64"
  - build_amd64:
      docker: docker:20.10
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_USER
      steps:
        - setup_remote_docker:
            docker_layer_caching: true
        - checkout
        - build-image-and-push:
            tag: "${DOCKERHUB_USER}/grpc-generator-go:${CIRCLE_TAG}"
            arch: "amd64"
  - build_manifest:
      docker: docker:20.10
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_USER
      steps:
        - setup_remote_docker:
            docker_layer_caching: true
        - run: |
            export TAG="${DOCKERHUB_USER}/grpc-generator-go:${CIRCLE_TAG}"
            export TAG_LATEST="${DOCKERHUB_USER}/grpc-generator-go:latest"
              
            docker manifest create $TAG_LATEST ${TAG}-amd64 ${TAG}-arm64
            docker manifest push $TAG_LATEST

workflows:
  version: 2
  build_tag:
    jobs:
      - build_arm64:
        filters:
          branches:
            only:
              - none
          tags:
            only: /.*/
      - build_amd64:
        filters:
          branches:
            only:
              - none
          tags:
            only: /.*/
      - build_manifest:
          requires:
            - build_arm64
            - build_amd64
          filters:
            branches:
              only:
                - none
            tags:
              only: /.*/
