version: 2.1
commands:
  build-image-and-push:
    parameters:
      tag:
        type: string
      arch:
        type: string
    steps:
      - run: |
          docker build --platform=linux/<<parameters.arch>> -t <<parameters.tag>>-<<parameters.arch>> ./<<parameters.arch>>
          docker push <<parameters.tag>>-<<parameters.arch>>
  docker-login:
    steps:
      - run: |
          echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USER --password-stdin

jobs:
  build_arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - docker-login
      - build-image-and-push:
          tag: "${DOCKERHUB_USER}/grpc-generator-go:${CIRCLE_TAG}"
          arch: "arm64"
  build_amd64:
    docker:
      - image: docker:20.10
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.11
      - checkout
      - docker-login
      - build-image-and-push:
          tag: "${DOCKERHUB_USER}/grpc-generator-go:${CIRCLE_TAG}"
          arch: "amd64"
  build_manifest:
    docker:
      - image: docker:20.10
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.11
      - docker-login
      - run: |
          export TAG="${DOCKERHUB_USER}/grpc-generator-go:${CIRCLE_TAG}"
          export TAG_LATEST="${DOCKERHUB_USER}/grpc-generator-go:latest"
              
          docker manifest create $TAG_LATEST ${TAG}-amd64 ${TAG}-arm64
          docker manifest push $TAG_LATEST
          
          docker manifest create ${TAG} ${TAG}-amd64 ${TAG}-arm64
          docker manifest push ${TAG}

workflows:
  version: 2
  build_tag:
    jobs:
      - build_arm64:
          filters:
            branches:
              only:
                - none
            tags:
              only: /.*/
      - build_amd64:
          filters:
            branches:
              only:
                - none
            tags:
              only: /.*/
      - build_manifest:
          requires:
            - build_arm64
            - build_amd64
          filters:
            branches:
              only:
                - none
            tags:
              only: /.*/
