version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          export TAG="${DOCKERHUB_USER}/grpc-generator-go:${CIRCLE_TAG}"
          export TAG_LATEST="${DOCKERHUB_USER}/grpc-generator-go:latest"
          
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
        
          docker build --platform=linux/amd64 -t ${TAG}-amd64 ./amd64
          docker push ${TAG}-amd64
          
          docker build --platform=linux/arm64/v8 -t ${TAG}-arm64 ./arm64
          docker push ${TAG}-arm64
          
          docker manifest create $TAG ${TAG}-amd64 ${TAG}-arm64
          docker manifest annotate $TAG ${TAG}-arm64 --variant v8
          docker manifest push $TAG
          
          docker manifest create $TAG_LATEST ${TAG}-amd64 ${TAG}-arm64
          docker manifest annotate $TAG_LATEST ${TAG}-arm64 --variant v8
          docker manifest push $TAG_LATEST

workflows:
  version: 2
  build_tag:
    jobs:
      - build:
          filters:
            branches:
              only:
                - none
            tags:
              only: /.*/
